services:
  - type: web
    name: kitchen-app-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FLASK_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
